### ISSUE TITLE
Drop "C++" as a claimed targeted language.

### ISSUE THREAD

**Issue by eyalroz** [sheredom/subprocess.h#22]
C code is very rarely appropriate as C++ code. It is non-idiomatic, resource-unsafe, and difficult to combine with common C++ libraries and other idiomatic code.

I'd say it is "also usable in C++", but not beyond that.

**Comment by rwhair** [comment]
Or you could save a few characters and just call it “usable”.

**Comment by StuartDAdams** [comment]
I have to disagree. If C code compiles with a C++ compiler then it is also C++. If this code could only be compiled with a C compiler, you would have a point, but this code has clearly been written to work from both C and C++ contexts. Also, just because it isn't "idiomatic" doesn't mean it isn't C++.

**Comment by cyberkm** [comment]
Eyal, if a code can be compiled by a c++ compiler that follows c++ standard, that means the code is written in c++. It's as simple as it gets. Everything else is just speculations and personal preferences.

**Comment by eyalroz** [comment]
It seems you have not read what I've written and have answered a different claim. Please re-read it.

**Comment by sheredom** [comment]
Thanks for your interest in my library, I love serving the C++ community with code that **is C++ because it can be compiled by any C++ compiler**.

I won't be taking your suggestion on board as any idealogical statements like  _'C++ should be like X'_ are not worth getting out of bed over.
